# Generated by Django 2.2.2 on 2019-06-15 21:15

import django.contrib.gis.db.models.fields
from django.db import migrations
import json
from django.contrib.gis.geos import fromstr
from pathlib import Path


DATA_FILENAME = 'data.json'
def load_data(apps, schema_editor):
    Localization = apps.get_model('location', 'Localization')
    jsonfile = Path(__file__).parents[2] / DATA_FILENAME

    with open(str(jsonfile)) as datafile:
        objects = json.load(datafile)
        for obj in objects['elements']:
            try:
                objType = obj['type']
                if objType == 'node':
                    tags = obj['tags']
                    name = tags.get('name','no-name')
                    longitude = obj.get('lon', 0)
                    latitude = obj.get('lat', 0)
                    location = fromstr(f'POINT({longitude} {latitude})', srid=4326)
                    Localization(name=name, location = location).save()
            except KeyError:
                pass

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('place', '1_initial'),
    ]


    operations = [
        migrations.RunPython(load_data),


    ]
