# Generated by Django 2.2.2 on 2019-06-15 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geolocdamkio', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            name='Localization',
        ),
    ]
